/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as AuthenticatedConexaoRouteImport } from './routes/_authenticated/conexao'
import { Route as AuthenticatedGruposRouteImport } from './routes/_authenticated/grupos'
import { Route as AuthenticatedHorariosRouteImport } from './routes/_authenticated/horarios'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'
import { Route as AuthenticatedPlanosRouteImport } from './routes/_authenticated/planos'
import { Route as AuthenticatedPreviewIaRouteImport } from './routes/_authenticated/preview-ia'
import { Route as AuthenticatedProdutosRouteImport } from './routes/_authenticated/produtos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedConexaoRoute = AuthenticatedConexaoRouteImport.update({
  id: '/conexao',
  path: '/conexao',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGruposRoute = AuthenticatedGruposRouteImport.update({
  id: '/grupos',
  path: '/grupos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHorariosRoute = AuthenticatedHorariosRouteImport.update({
  id: '/horarios',
  path: '/horarios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlanosRoute = AuthenticatedPlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPreviewIaRoute = AuthenticatedPreviewIaRouteImport.update({
  id: '/preview-ia',
  path: '/preview-ia',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProdutosRoute = AuthenticatedProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/termos': typeof TermosRoute
  '/conexao': typeof AuthenticatedConexaoRoute
  '/grupos': typeof AuthenticatedGruposRoute
  '/horarios': typeof AuthenticatedHorariosRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/planos': typeof AuthenticatedPlanosRoute
  '/preview-ia': typeof AuthenticatedPreviewIaRoute
  '/produtos': typeof AuthenticatedProdutosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/termos': typeof TermosRoute
  '/conexao': typeof AuthenticatedConexaoRoute
  '/grupos': typeof AuthenticatedGruposRoute
  '/horarios': typeof AuthenticatedHorariosRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/planos': typeof AuthenticatedPlanosRoute
  '/preview-ia': typeof AuthenticatedPreviewIaRoute
  '/produtos': typeof AuthenticatedProdutosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/termos': typeof TermosRoute
  '/_authenticated/conexao': typeof AuthenticatedConexaoRoute
  '/_authenticated/grupos': typeof AuthenticatedGruposRoute
  '/_authenticated/horarios': typeof AuthenticatedHorariosRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRoute
  '/_authenticated/planos': typeof AuthenticatedPlanosRoute
  '/_authenticated/preview-ia': typeof AuthenticatedPreviewIaRoute
  '/_authenticated/produtos': typeof AuthenticatedProdutosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/termos'
    | '/conexao'
    | '/grupos'
    | '/horarios'
    | '/painel'
    | '/planos'
    | '/preview-ia'
    | '/produtos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/termos'
    | '/conexao'
    | '/grupos'
    | '/horarios'
    | '/painel'
    | '/planos'
    | '/preview-ia'
    | '/produtos'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/termos'
    | '/_authenticated/conexao'
    | '/_authenticated/grupos'
    | '/_authenticated/horarios'
    | '/_authenticated/painel'
    | '/_authenticated/planos'
    | '/_authenticated/preview-ia'
    | '/_authenticated/produtos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  TermosRoute: typeof TermosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/conexao': {
      id: '/_authenticated/conexao'
      path: '/conexao'
      fullPath: '/conexao'
      preLoaderRoute: typeof AuthenticatedConexaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/grupos': {
      id: '/_authenticated/grupos'
      path: '/grupos'
      fullPath: '/grupos'
      preLoaderRoute: typeof AuthenticatedGruposRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/horarios': {
      id: '/_authenticated/horarios'
      path: '/horarios'
      fullPath: '/horarios'
      preLoaderRoute: typeof AuthenticatedHorariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/planos': {
      id: '/_authenticated/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof AuthenticatedPlanosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/preview-ia': {
      id: '/_authenticated/preview-ia'
      path: '/preview-ia'
      fullPath: '/preview-ia'
      preLoaderRoute: typeof AuthenticatedPreviewIaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/produtos': {
      id: '/_authenticated/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof AuthenticatedProdutosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedConexaoRoute: typeof AuthenticatedConexaoRoute
  AuthenticatedGruposRoute: typeof AuthenticatedGruposRoute
  AuthenticatedHorariosRoute: typeof AuthenticatedHorariosRoute
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRoute
  AuthenticatedPlanosRoute: typeof AuthenticatedPlanosRoute
  AuthenticatedPreviewIaRoute: typeof AuthenticatedPreviewIaRoute
  AuthenticatedProdutosRoute: typeof AuthenticatedProdutosRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedConexaoRoute: AuthenticatedConexaoRoute,
  AuthenticatedGruposRoute: AuthenticatedGruposRoute,
  AuthenticatedHorariosRoute: AuthenticatedHorariosRoute,
  AuthenticatedPainelRoute: AuthenticatedPainelRoute,
  AuthenticatedPlanosRoute: AuthenticatedPlanosRoute,
  AuthenticatedPreviewIaRoute: AuthenticatedPreviewIaRoute,
  AuthenticatedProdutosRoute: AuthenticatedProdutosRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  TermosRoute: TermosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
